name: Firebase Hosting Deploy

on:
  push:
    branches:
      - develop  # o la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # ajusta si usas una versión diferente

      - name: Install dependencies
        run: |
          npm install

      - name: Build the app
        run: |
          npm run start

      - name: Deploy to Firebase
        uses: wzieba/firebase-action@v2.2.0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ARQUITECH }}'
          channelId: live
          projectId: arquitech

