name: Firebase Hosting Deploy

# Desencadenar el flujo de trabajo en push a la rama principal
on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Usar una máquina Ubuntu para el entorno de GitHub Actions
    steps:
      # Clonar el repositorio
      - uses: actions/checkout@v4

      # Configurar Node.js (Angular requiere Node.js)
      - uses: actions/setup-node@v4
        with:
          node-version: '20' # Usa una versión compatible con tu proyecto Angular (puedes verificarla en package.json)
          cache: 'npm' # Cache para acelerar la instalación de dependencias

      # Instalar dependencias del proyecto
      - name: Install Dependencies
        run: npm ci # npm ci es más rápido y fiable para CI/CD que npm install

      # Construir el proyecto Angular
      - name: Build Angular Project
        run: npm run build -- --configuration production # Construye con configuración de producción
        env:
          NODE_OPTIONS: --max-old-space-size=4096 # Opcional: Aumenta la memoria para builds grandes

      # Instalar Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Desplegar a Firebase Hosting
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Token de Firebase para autenticación

